<?php

namespace HamzaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InsectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsectRepository extends EntityRepository
{
}
