<?php

namespace HamzaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TemplatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplatesRepository extends EntityRepository
{
}
